import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react";
import { connectWallet } from "./utils/interact";
import HelloWord from './HelloWord';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <HelloWord />
    </div>
  )
}
